[package]
name = "hmac_sha1"
type = "lib"
authors = [""]
compiler_version = "0.10.5"

[dependencies]
sha1 = { tag = "v0.0.3", git = "https://github.com/michaelelliot/noir-sha1", directory = "crates/noir-sha1" }